In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,roc_auc_score,classification_report,f1_score
from sklearn import metrics

In [3]:
df_heart = pd.read_csv("Datasets\heart.csv")

In [4]:
df_heart.head(10)


age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   
5   57    1   0     140   192    0        1       148     0      0.4    1   
6   56    0   1     140   294    0        0       153     0      1.3    1   
7   44    1   1     120   263    0        1       173     0      0.0    2   
8   52    1   2     172   199    1        1       162     0      0.5    2   
9   57    1   2     150   168    0        1       174     0      1.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  
5    0      1       1  
6    0      2       1  
7    0      3       1  
8    0      3       1  
9    0      2       1

In [5]:
df_heart = df_heart[(df_heart["thalachh"] > 100) & (df_heart["thalachh"] < 180) ]

In [6]:
df_heart = df_heart[(df_heart["oldpeak"] >= 0) & (df_heart["oldpeak"] <= 3) ]

In [7]:
df_heart = df_heart.drop("fbs" , axis=1)
df_heart = df_heart.drop("trtbps" , axis=1)
df_heart = df_heart.drop("chol" , axis=1)

In [8]:
df_heart.drop_duplicates(inplace=True)

# Preprocessing et séparation de l'output du df

In [9]:
def preprocessing_inputs(df_heart, scaler):
    df_heart = df_heart.copy()
    
    y = df_heart["output"].copy()
    X = df_heart.drop("output", axis=1).copy()
    
    return X, y 



In [10]:
X, y = preprocessing_inputs(df_heart, MinMaxScaler())

In [11]:
X

age  sex  cp  restecg  thalachh  exng  oldpeak  slp  caa  thall
0     63    1   3        0       150     0      2.3    0    0      1
2     41    0   1        0       172     0      1.4    2    0      2
3     56    1   1        1       178     0      0.8    2    0      2
4     57    0   0        1       163     1      0.6    2    0      2
5     57    1   0        1       148     0      0.4    1    0      1
..   ...  ...  ..      ...       ...   ...      ...  ...  ...    ...
296   63    0   0        1       136     1      0.0    1    0      2
298   57    0   0        1       123     1      0.2    1    0      3
299   45    1   3        1       132     0      1.2    1    0      3
301   57    1   0        1       115     1      1.2    1    1      3
302   57    0   1        0       174     0      0.0    1    1      2

[256 rows x 10 columns]

In [12]:
y

0      1
2      1
3      1
4      1
5      1
      ..
296    0
298    0
299    0
301    0
302    0
Name: output, Length: 256, dtype: int64

#  split test et training

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,stratify=y, random_state=0)

In [14]:
print(X.shape, X_train.shape, X_test.shape)

(256, 10) (204, 10) (52, 10)


#  REGRESSION LOGISTIQUE (84,61%)

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train, y_train)

C:\Users\nolan\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

In [18]:
training_data_accuracy

0.8382352941176471

In [19]:
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, y_test)

In [20]:
testing_data_accuracy

0.8461538461538461

In [21]:
print("le score d'accuracy est de : ", testing_data_accuracy*100, "%")

le score d'accuracy est de :  84.61538461538461 %


#  DECISION TREE (73,07%)

In [22]:
model_2 = DecisionTreeClassifier(random_state = 0)

In [23]:
model_2.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [24]:
X_train_prediction_2 = model_2.predict(X_train)
training_data_accuracy_2 = accuracy_score(X_train_prediction_2, y_train)

In [25]:
training_data_accuracy_2

1.0

In [26]:
X_test_prediction_2 = model_2.predict(X_test)
testing_data_accuracy_2 = accuracy_score(X_test_prediction_2, y_test)

In [27]:
testing_data_accuracy_2

0.7307692307692307

# RANDOM FOREST (88,46%)

In [28]:
model_3 = RandomForestClassifier(random_state = 0, n_estimators = 120)

In [29]:
model_3.fit(X_train, y_train)

RandomForestClassifier(n_estimators=120, random_state=0)

In [30]:
X_train_prediction_3 = model_3.predict(X_train)
training_data_accuracy_3 = accuracy_score(X_train_prediction_3, y_train)
training_data_accuracy_3

1.0

In [31]:
X_test_prediction_3 = model_3.predict(X_test)
testing_data_accuracy_3 = accuracy_score(X_test_prediction_3, y_test)
testing_data_accuracy_3

0.8846153846153846

# Kn neighbours (71,15%)

In [32]:
model_4 = KNeighborsClassifier()

In [33]:
model_4.fit(X_train, y_train)

KNeighborsClassifier()

In [34]:
X_train_prediction_4 = model_4.predict(X_train)
training_data_accuracy_4 = accuracy_score(X_train_prediction_4, y_train)
training_data_accuracy_4

0.7598039215686274

In [35]:
X_test_prediction_4 = model_4.predict(X_test)
testing_data_accuracy_4 = accuracy_score(X_test_prediction_4, y_test)
testing_data_accuracy_4

0.7115384615384616

#  Construction d'un système prédictif


In [36]:
print('\n La matrice de confusion : \n', confusion_matrix(y_test, X_test_prediction))
print('\n La matrice de confusion : \n', confusion_matrix(y_test, X_test_prediction_2))
print('\n La matrice de confusion : \n', confusion_matrix(y_test, X_test_prediction_3))
print('\n La matrice de confusion : \n', confusion_matrix(y_test, X_test_prediction_4))


 La matrice de confusion : 
 [[19  4]
 [ 4 25]]

 La matrice de confusion : 
 [[15  8]
 [ 6 23]]

 La matrice de confusion : 
 [[19  4]
 [ 2 27]]

 La matrice de confusion : 
 [[13 10]
 [ 5 24]]


In [37]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [38]:
print("Precision score: {}".format(precision_score(y_test,X_test_prediction_3)))
print("Recall score: {}".format(recall_score(y_test,X_test_prediction_3)))
print("F1 score: {}".format(f1_score(y_test,X_test_prediction_3)))

Precision score: 0.8709677419354839
Recall score: 0.9310344827586207
F1 score: 0.9


In [39]:
random_forest_params = { 
                        'min_samples_leaf': [1, 2, 4],
                        'min_samples_split': [2, 5, 10]
                       
                        }


model_opti = GridSearchCV(RandomForestClassifier(), random_forest_params)

In [40]:
model_opti.fit(X_train, y_train)


model_opti.best_score_

0.7941463414634147

In [41]:
log_reg = model_opti.best_estimator_

In [42]:
log_reg

RandomForestClassifier(min_samples_split=5)